tasks/urls.py
from django.urls import path

from . import views


app_name = "tasks"


urlpatterns = [
    path('', views.index, name='index'),
    
    # path('list/', views.tasks_list, name='list'),
    # path('create/', views.task_create, name='create'),
    path('add-task/', views.add_task, name='api-add-task'),
    path("list/", views.TaskListView.as_view(), name="list"),
    path("create/", views.TaskCreateView.as_view(), name="create"),

    path('complete/<int:uid>', views.complete_task, name='complete'),
    path('delete/<int:uid>', views.delete_task, name='delete'),
    path("details/<int:pk>", views.TaskDetailsView.as_view(), name="details"),

    path("edit/<int:pk>", views.TaskEditView.as_view(), name='edit'),
    path("export/", views.TaskExportView.as_view(), name="export"),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls', namespace="tasks")),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/models.py
from django.db import models

# Create your models here.

from django.urls import reverse

from django.contrib.auth.models import User


class TodoItem(models.Model):
    PRIORITY_HIGH = 1
    PRIORITY_MEDIUM = 2
    PRIORITY_LOW = 3

    PRIORITY_CHOICES = [
        (PRIORITY_HIGH, "Высокий приоритет"),
        (PRIORITY_MEDIUM, "Средний приоритет"),
        (PRIORITY_LOW, "Низкий приоритет"),
    ]

    description = models.CharField(max_length=64)
    is_completed = models.BooleanField("выполнено", default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='tasks')
    priority = models.IntegerField(
        "Приоритет", choices=PRIORITY_CHOICES, default=PRIORITY_MEDIUM
    )

    def __str__(self):
        return self.description.lower()

    def get_absolute_url(self):
        return reverse("tasks:details", args=[self.pk])    


    class Meta:
        ordering = ('-created',)

tasks/forms.py
from django import forms

from tasks.models import TodoItem


class AddTaskForm(forms.Form):
    description = forms.CharField(max_length=64, label='')


class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ('description', "priority")
        labels = {"description": "Описание", "priority": ""}


class TodoItemExportForm(forms.Form):
    prio_high = forms.BooleanField(
        label="высокая важность", initial=True, required=False
    )
    prio_med = forms.BooleanField(
        label="средней важности", initial=True, required=False
    )
    prio_low = forms.BooleanField(
        label="низкой важности", initial=False, required=False
    )

tasks/views.py
from django.shortcuts import render, redirect

# Create your views here.

from django.http import HttpResponse
from tasks.models import TodoItem
from tasks.forms import TodoItemForm, AddTaskForm, TodoItemExportForm


from django.views import View
from django.views.generic import ListView
from django.views.generic.detail import DetailView

from django.urls import reverse

from django.contrib.auth.decorators import login_required

from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib import messages


from django.core.mail import send_mail
from django.conf import settings

from django.db.models import Q

########
@login_required
def index(request):
    send_mail(
        "Привет от django",
        "Письмо отправленное из приложения",
        settings.EMAIL_HOST_USER, 
        ["yuraskakun@ukr.net"],
        fail_silently=False
    )
    return HttpResponse("Примитивный ответ из приложения tasks")

# def index(request):
#     return HttpResponse("Примитивный ответ из приложения tasks")
########

########
def tasks_list(request):
	all_tasks = TodoItem.objects.all()
	return render(
		request,
		'tasks/list.html',
		{'tasks': all_tasks}
	)
########

########
def complete_task(request, uid):
	t = TodoItem.objects.get(id=uid)
	t.is_completed = True
	t.save()
	return HttpResponse("OK")
########

########
def delete_task(request, uid):
	t = TodoItem.objects.get(id=uid)
	t.delete()
    # messages.success(request, "Задача удалена")
	return redirect(reverse("tasks:list"))
    # return redirect("/tasks/list")

########

########
# def  task_create(request):
# 	return render(request, "tasks/create.html")	

def add_task(request):
	if request.method == "POST":
		desc = request.POST["description"]
		t = TodoItem(description=desc)
		t.save()
	return redirect(reverse("tasks:list"))



# def task_create(request):
#     form = AddTaskForm()
#     return render(request, "tasks/create.html", {"form": form})

	
# def task_create(request):
#     if request.method == "POST":
#         form = AddTaskForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             desc = cd["description"]
#             t = TodoItem(description=desc)
#             t.save()
#             return redirect("/tasks/list")
#     else:
#         form = AddTaskForm()
#
#     return render(request, "tasks/create.html", {"form": form})

	
def task_create(request):
    if request.method == "POST":
        form = TodoItemForm(request.POST)
        if form.is_valid():
            form.save()                        # create object in DB
            return redirect(reverse("tasks:list"))
    else:
        form = TodoItemForm()
    return render(request, "tasks/create.html", {"form": form})
########


########
"""
class TaskListView(ListView):
    # queryset = TodoItem.objects.all()
    # context_object_name = "tasks"
    # template_name = "tasks/list.html"

    model = TodoItem
    context_object_name = "tasks"
    template_name = "tasks/list.html"

    def get_queryset(self):
        qs = super().get_queryset()
        u = self.request.user
        if u.is_anonymous:
            return []
        return qs.filter(owner=u)

    # def get_queryset(self):        ### or this variant
    #     u = self.request.user
    #     if u.is_anonymous:
    #         return []
    #     return u.tasks.all()
"""

class TaskListView(LoginRequiredMixin, ListView):
    model = TodoItem
    context_object_name = "tasks"
    template_name = "tasks/list.html"

    def get_queryset(self):        
        u = self.request.user
        return u.tasks.all()
########



    
########
# class TaskCreateView(View):    
#     def post(self, request, *args, **kwargs):
#         form = TodoItemForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect("/tasks/list")

#         return render(request, "tasks/create.html", {"form": form})

#     def get(self, request, *args, **kwargs):
#         form = TodoItemForm()
#         return render(request, "tasks/create.html", {"form": form})


""""
class TaskCreateView(View):
    def my_render(self, request, form):
        return render(request, "tasks/create.html", {"form": form})    

    def post(self, request, *args, **kwargs):
        form = TodoItemForm(request.POST)
        if form.is_valid():
            form.save()
            # return redirect("/tasks/list")
            return reverse("tasks:list")

        return self.my_render(request, form)

    def get(self, request, *args, **kwargs):
        form = TodoItemForm()
        return self.my_render(request, form)
"""

class TaskCreateView(View):
    def my_render(self, request, form):
        return render(request, "tasks/create.html", {"form": form})    

    def post(self, request, *args, **kwargs):
        form = TodoItemForm(request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            # return redirect("/tasks/list")
            return redirect(reverse("tasks:list"))

        return self.my_render(request, form)

    def get(self, request, *args, **kwargs):
        form = TodoItemForm()
        return self.my_render(request, form)
########

class TaskDetailsView(DetailView):
    model = TodoItem
    template_name = 'tasks/details.html'
    # result this class --> object


class TaskEditView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        t = TodoItem.objects.get(id=pk)
        form = TodoItemForm(request.POST, instance=t)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            messages.success(request, "Задача отредактирована")
            return redirect(reverse("tasks:list"))
    
        return render(request, "tasks/edit.html", {"form": form, "task": t})

    def get(self, request, pk, *args, **kwargs):
        t = TodoItem.objects.get(id=pk)
        form = TodoItemForm(instance=t)
        return render(request, "tasks/edit.html", {"form": form, "task": t})


class TaskExportView(LoginRequiredMixin, View):
    def generate_body(self, user, priorities):
        q = Q()
        if priorities["prio_high"]:
            q = q | Q(priority=TodoItem.PRIORITY_HIGH)
        if priorities["prio_med"]:
            q = q | Q(priority=TodoItem.PRIORITY_MEDIUM)
        if priorities["prio_low"]:
            q = q | Q(priority=TodoItem.PRIORITY_LOW)
        tasks = TodoItem.objects.filter(owner=user).filter(q).all()

        body = "Ваши задачи и приоритеты:\n"
        for t in list(tasks):
            if t.is_completed:
                body += "[x] {} ({})\n".format(t.description,t.get_priority_display())
            else:
                body += "[ ] {} ({})\n".format(t.description,t.get_priority_display()) 
        
        return body

    def post(self, request, *args, **kwargs):
        form = TodoItemExportForm(request.POST)
        if form.is_valid():
            email = request.user.email
            body = self.generate_body(request.user, form.cleaned_data)
            send_mail("Задачи", body, settings.EMAIL_HOST_USER, [email])
            messages.success(
                request, "Задачи были отправлены на почту %s" % email)
        else:
            messages.error(request, "Что-то пошло не так, попробуйте ещё раз")
        return redirect(reverse("tasks:list"))

    def get(self, request, *args, **kwargs):
        form = TodoItemExportForm()
        return render(request, "tasks/export.html", {"form": form}) 
        

tasks/templates/tasks/create.html
{% extends "base.html" %}
{% load static %}

{% block title %}Создать задачу{% endblock%}
       
  
{% block main_content %}
  <h1>Создать задачу</h1>
  <form action="." method="post">
  	{{ form.as_p }}
  	{% csrf_token %}
    <p><button class="add" type="submit">Добавить</button></p>
  </form>
{% endblock %} 

tasks/templates/tasks/create_0001.html
{% extends "tasks/base.html" %}


{% block title %}Создать задачу{% endblock%}
       
  
{% block main_content %}
  <h1>Создать задачу</h1>
  <form action="/tasks/add-task/" method="post">
  	{% csrf_token %}
    <input type="text" name="description" class="form-control"/>
    <button class="add" type="submit">+</button>
  </form>
{% endblock %} 

tasks/templates/tasks/details.html
{% extends "base.html" %}
{% load static %}

{% block title %}Задача {{ object.id }}{% endblock %}

{% block extra_head %}
  <link rel="stylesheet"
href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
integrity="sha384-
lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"
crossorigin="anonymous">
{% endblock %}

{% block main_content %}
  <h1>Задача</h1>
  <p><b>Описание</b>: {{ object }}</p>
  <ul>
    <li>
      {{ object.is_completed|yesno:"Выполнена,Не выполнена" }}
   <!--  {% if object.is_completed %}
        Задача выполнена
    {% else %}
        Задача ещё не выполнена
    {% endif %} -->
    </li>
    <li><i class="far fa-calendar-alt"></i>&nbsp;Создана: 
    {{ object.created|date:"Y-b-d H:i" }}</li>
    <li><i class="far fa-clock"></i>&nbsp;Последнее изменение: 
    {{ object.updated }}</li>
    <li><i class="far fa-edit"></i>&nbsp;<a href="{% url "tasks:edit" object.pk %}">Редактировать</a></li>
  </ul>
  <i class="fas fa-clipboard-list"></i>&nbsp;
  <a href="{% url "tasks:list" %}">Назад к списку</a>
{% endblock %}

tasks/templates/tasks/edit.html
{% extends "base.html" %}
{% load static %}

{% block title %}Изменить задачу{% endblock%}
       
  
{% block main_content %}
  <h1>Поменять задачу</h1>
  <form action="{% url "tasks:edit" task.pk %}" method="post">
  	{{ form.as_p }}
  	{% csrf_token %}
    <p><button class="add" type="submit">Сохранить</button></p>
  </form>
{% endblock %} 

tasks/templates/tasks/export.html
{% extends "base.html" %}

{% block title %}Экспорт{% endblock %}

{% block main_content %}
  <h1>Экспорт задач</h1>
  <p>На вашу почту придёт емейл с задачами. Уточните список.</p>
  <form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><button class="add" type="submit">Жмяк</button></p>
  </form>
{% endblock %}

tasks/templates/tasks/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Задачи на день{% endblock%}
    
{% block extra_head %}
  <script src="{% static 'js/script.js' %}"></script>
{% endblock %}        
  
{% block main_content %}
  <h1>Текущие задачи</h1>
  <p><i class="fa fa-download"></i>&nbsp;<a href="{% url "tasks:export" %}">экспорт</a></h1>
  <ul id="todo-list">
  {% for task in tasks %}
    {% if task.is_completed %}
    <li class="completed">
      <input class='checkbox'  data-uid={{ task.id }} type='checkbox' disabled='disabled' checked='checked'/>
    {% else %}
    <li>
      <input class='checkbox'  data-uid={{ task.id }} type='checkbox' />
    {% endif %}
      {% if task.priority == task.PRIORITY_HIGH %}
      <span class="badge badge-pill badge-danger">&nbsp;</span>
      {% elif task.priority == task.PRIORITY_MEDIUM %}
      <span class="badge badge-pill badge-secondary">&nbsp;</span>
      {% elif task.priority == task.PRIORITY_LOW %}
      <span class="badge badge-pill badge-success">&nbsp;</span>
      {% endif %}
      <a href={% url "tasks:details" task.id %}>{{ task }}</a>
      <a class="remove" href={% url "tasks:delete" task.id %}>X</a>
      <hr/>
    </li>
  {% endfor %}
  </ul>
{% endblock %}   

tasks/templates/tasks/list_0001.html
{% extends "tasks/base.html" %}
{% load static %}

{% block title %}Задачи на день{% endblock%}
    
{% block extra_head %}
  <script src="{% static 'js/script.js' %}"></script>
{% endblock %}        
  
{% block main_content %}
  <h1>Текущие задачи</h1>
  <ul id="todo-list">
  {% for task in tasks %}
    {% if task.is_completed %}
    <li class="completed">
      <input class='checkbox'  data-uid={{ task.id }} type='checkbox' disabled='disabled' checked='checked'/>
    {% else %}
    <li>
      <input class='checkbox'  data-uid={{ task.id }} type='checkbox' />
    {% endif %}
      {{ task }}
      <a class="remove" href="/tasks/delete/{{ task.id }}">X</a>
      <hr/>
    </li>
  {% endfor %}
  </ul>
{% endblock %}   