tasks/urls.py
from django.urls import path

from . import views


app_name = "tasks"


urlpatterns = [
    path('', views.index, name='index'),
    
    # path('list/', views.tasks_list, name='list'),
    # path('create/', views.task_create, name='create'),
    path('add-task/', views.add_task, name='api-add-task'),
    path("list/", views.TaskListView.as_view(), name="list"),
    path("create/", views.TaskCreateView.as_view(), name="create"),

    path('complete/<int:uid>', views.complete_task, name='complete'),
    path('delete/<int:uid>', views.delete_task, name='delete'),
    path("details/<int:pk>", views.TaskDetailsView.as_view(), name="details"),

    path("edit/<int:pk>", views.TaskEditView.as_view(), name='edit'),
    path("export/", views.TaskExportView.as_view(), name="export"),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls', namespace="tasks")),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<html>
  <head>
    <title>{% block title %}Туду-дуду{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <link rel="stylesheet"
href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
integrity="sha384-
Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
crossorigin="anonymous">

    <link rel="stylesheet"
href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
integrity="sha384-
GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
crossorigin="anonymous">

    <script src="http://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script
src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
integrity="sha384-
wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
crossorigin="anonymous"></script>
<script
src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
integrity="sha384-
B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
crossorigin="anonymous"></script>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    <div class="container">
      <div class="row">

        <div class="side_bar col">
          {% block side_bar %}
            {% if user.is_authenticated %}
              <p>{{ user.first_name }}</p>
              

              <ul>
                <li><a href="{% url "edit" %}">профиль</a></li>
                <li><a href="{% url "tasks:create" %}">добавить задачу</a></li>
                <li><a href="{% url "tasks:list" %}">задачи</a></li>
                <li><a href="{% url "logout" %}">выйти</a></li>
              </ul>
            {% endif %}
          {% endblock %}
        </div>

        <div class="main_content col-8">
          {% if messages %}
          <div class="row">
            <ul class="messages">
              {% for message in messages %}
              <li class="alert alert-{{ message.tags }} alert-dismissable">
              {{ message }}
              <a href="#" class="close" data-dismiss="alert">x</a>
              </li>
              {% endfor %}
            </ul>
          </div>
          {% endif %}

          {% block main_content %}
          {% endblock %}
        </div>

      </div>
    </div>
  </body>
</html>

templates/base_0001.html
{% load static %}
<html>
  <head>
    <title>{% block title %}Туду-дуду{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <script src="http://code.jquery.com/jquery-3.3.1.min.js"></script>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
  <div class="container">
    {% block main_content %}
    {% endblock %}
  </div>
  </body>
</html>